# -*- coding: utf-8 -*-
"""Vendas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-YEXKh5veuxyEwQx9Du92YIib6lFJXNK

### **1.   Importando a Base de Dados**
"""

import pandas as pd

# Importando a tabela
tabela_vendas = pd.read_excel("Vendas.xlsx")

# Exibindo as 15 primeiras linhas da tabela só para termos um panorama geral
display(tabela_vendas.head(15))

"""### **2. Visualizar o Faturamento Total por Loja**

**A partir da tabela abaixo, fica claro que a loja Iguatemi é responsável pela maior parte do faturamento (74,6%) da empresa. Vamos usar os dados dessa loja para retirar insights que possam aumentar as vendas da empresa.**
"""

# Criando a tabela
faturamento_por_loja = tabela_vendas[["ID Loja", "Valor Final"]].groupby("ID Loja").sum()
faturamento_por_loja = faturamento_por_loja.sort_values(by="Valor Final", ascending=False) # Ordenando o faturamento em ordem decrescente

# Criando coluna de % do faturamento
faturamento_total = tabela_vendas["Valor Final"].sum() # Faturamento total
faturamento_por_loja["% Faturamento"] = tabela_vendas[["ID Loja", "Valor Final"]].groupby("ID Loja").sum() # Coluna criada
faturamento_por_loja["% Faturamento"] = (faturamento_por_loja["Valor Final"] / faturamento_total) * 100 # Cálculo da % do faturamento
faturamento_por_loja["% Faturamento"] = round((faturamento_por_loja["% Faturamento"]), 1) # Arredonando cálculo para 1 casa decimal
faturamento_por_loja["% Faturamento"] = faturamento_por_loja["% Faturamento"].astype(str) + "%" # Formatando para %

# Transformando Faturamento em Moeda
faturamento_por_loja["Valor Final"] = faturamento_por_loja["Valor Final"].map("R$ {:,.2f}".format)

display(faturamento_por_loja)

"""###**3. Visualizar Faturamento dos Produtos Vendidos por Loja**

**A partir da tabela abaixo, fica claro que a Bermuda Liso é responsável pela maior parte do faturamento da empresa. Ela corresponde a 65,4% do faturamento total.**
"""

# Criando tabela de produtos por loja
faturamento_produtos_por_loja = tabela_vendas[["ID Loja", "Produto", "Valor Final"]].groupby(["ID Loja", "Produto"]).sum()
faturamento_produtos_por_loja = faturamento_produtos_por_loja.groupby("ID Loja", group_keys=False)

# Ordendo faturamento por ordem decrescente
faturamento_produtos_por_loja = faturamento_produtos_por_loja.apply(lambda x: x.sort_values(by="Valor Final", ascending=False))
faturamento_produtos_por_loja["Valor Final"] = faturamento_produtos_por_loja["Valor Final"].apply(lambda x: "R$ {:,.2f}".format(x)) #formatando em moeda

display(faturamento_produtos_por_loja)

"""**Verificando qual a proporção do faturamento da Bermuda Liso em relação ao faturamento total:**"""

# Filtrando as linhas onde o Produto é "Bermuda Liso"
faturamento_bermuda_liso = tabela_vendas[tabela_vendas["Produto"] == "Bermuda Liso"]

# Calculando a soma dos valores finais para o produto "Bermuda Liso"
soma_faturamento_bermuda_liso = faturamento_bermuda_liso["Valor Final"].sum()

print((round((soma_faturamento_bermuda_liso/faturamento_total) * 100, 1)), "%")

"""### **4. Verificando a Quantidade de Produtos "Bermuda Liso" Vendidos por Loja**

**Somente a loja Iguatemi Campinas vende o produto "Bermuda Liso".**
"""

# Filtrando os dados para incluir apenas o produtos "Bermuda Liso"
produtos_liso_por_loja = tabela_vendas[tabela_vendas['Produto'] == 'Bermuda Liso']

# Criando uma tabela com a quantidade de produtos "Bermuda Liso" vendidos por loja
contagem_liso_por_loja = produtos_liso_por_loja.pivot_table(index='ID Loja', values='Quantidade', aggfunc='sum', fill_value=0)

# Exibindo a tabela
display(contagem_liso_por_loja)

"""# **Conclusões**"""